# Generated by Django 3.2.14 on 2022-08-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
