version: "3.4"

services:
  mikro:
    build: .
    command: bash run-debug.sh
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace
    ports:
      - 8045:8045
      
networks:
  default:
    external:
      name: dev

volumes:
  mytest: