version: "3.4"

services:
  elements:
    build: .
    command: bash run.sh
    ports:
      - 8080:8080
  blagi:
    image: postgres:12.6-alpine
    environment:
      POSTGRES_DB: hello_blagi
      POSTGRES_PASSWORD: hello_blagi
      POSTGRES_USER: hello_blagi
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    command: server /export
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: weak_access_key
      MINIO_SECRET_KEY: weak_secret_key
    volumes:
        - mytest:/export



networks:
  default:
    external:
      name: dev

    
volumes:
  mytest:

