# Generated by Django 6.0.6 on 2026-10-08 13:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arraydataset',
            name='stored_spec',
            field=models.JSONField(default=list, help_text='What this dataset structurally is: the raw ArrayDatasetSpec values (one spatial member plus a modifier per acquisition axis) that its intrinsic axes satisfy at its level-0 shape -- an axis counts only when it has more than one position -- materialized at creation by the axis writer from core.logic.coords.specs_for_axes. Immutable because the axes and the shape are, so it cannot disagree with them. Read it back as enum members through the `spec` property. Empty while the intrinsic system does not exist yet.'),
        ),
        migrations.AlterField(
            model_name='historicalarraydataset',
            name='stored_spec',
            field=models.JSONField(default=list, help_text='What this dataset structurally is: the raw ArrayDatasetSpec values (one spatial member plus a modifier per acquisition axis) that its intrinsic axes satisfy at its level-0 shape -- an axis counts only when it has more than one position -- materialized at creation by the axis writer from core.logic.coords.specs_for_axes. Immutable because the axes and the shape are, so it cannot disagree with them. Read it back as enum members through the `spec` property. Empty while the intrinsic system does not exist yet.'),
        ),
    ]
