# Generated by Django 6.0.6 on 2026-08-24 09:18

import django.contrib.postgres.indexes
import django.db.models.deletion
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0001_initial'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataarray',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store of the data array', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.zarrstore'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='file',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='file',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store of the file', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.bigfilestore'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, help_text='(ANNOTATION_COLLECTION) The annotation collection side of the link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filelink',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filelink',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='(DATASET) The array dataset side of the link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='core.arraydataset'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='file',
            field=models.ForeignKey(help_text='The file side of the link', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.file'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the folder', on_delete=django.db.models.deletion.CASCADE, related_name='created_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='folder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the folder', related_name='pinned_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='core.folder'),
        ),
        migrations.AddField(
            model_name='arraydataset',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='The folder this dataset is filed in. Organisational only -- it says nothing about where the data sits in space', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='array_datasets', to='core.folder'),
        ),
        migrations.AddField(
            model_name='annotationcollection',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='The folder this annotation collection is filed in. Organisational only -- it says nothing about the space the shapes are drawn in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_collections', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the tour', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.animation'),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization the tour belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The collection this annotation belongs to; its geometry is expressed in the collection's own coordinate system", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that drew this annotation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.annotation'),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='bbox_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this collection's stored bounding boxes are expressed in, when that is a system other than its own: the nearest intrinsic space its own system could reach at creation. Null when the boxes are in the collection's own space, which is the case whenever no chain resolves. Boxes only compare within one frame, and this names it. Written once at creation and immutable, because the stored boxes are numbers against it", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this collection's shapes are drawn in. All its annotations share it, so they share one placement story: the collection is related to other spaces by edges, the shapes just have vectors", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this annotation collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The folder this annotation collection is filed in. Organisational only -- it says nothing about the space the shapes are drawn in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this annotation collection belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this dataset's pixels are expressed in: its level-0 grid. PROTECT, because a space cannot be deleted while data lives in it", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the data source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The folder this dataset is filed in. Organisational only -- it says nothing about where the data sits in space', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.arraydataset'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization the data source belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this coordinate space', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this coordinate space belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalcoordinatesystem',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.file'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='membership',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The store of the file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.bigfilestore'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(ANNOTATION_COLLECTION) The annotation collection side of the link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(DATASET) The array dataset side of the link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.arraydataset'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='file',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The file side of the link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.file'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.filelink'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the folder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='membership',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalfolder',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(annotation) The annotation collection, owning its own coordinate system, whose drawn shapes this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this lens' voxels are expressed in. An unsliced lens shares its dataset's; a sliced one has its own, with a stored edge carrying the shift", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.arraydataset'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this collection's vertices are expressed in. An edge relates it to whatever the meshes were extracted from -- an identity when the grids agree, a scale when they do not", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this mesh collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The folder this mesh collection is filed in. Organisational only -- it says nothing about where the meshes sit in space', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this mesh collection belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The fabriks store holding this collection: one prefix with its manifest, both catalogs and every octree level. Its manifest is where the grid and the encoding come from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.fabriksstore'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalmetaschema',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalmetaschema',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmetaschema',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalmetaschema',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='world',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The space this scene composes its layers over: a shared world system created for convenience alongside the scene, or an adopted existing system -- a shared space, a dataset's intrinsic grid, a physical space, a collection's space. Never owned by the scene: many scenes can share it, it outlives each of them, and deleting a scene never deletes it. RESTRICT: while a scene is rooted in a space, neither the space nor its owning container can be deleted", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that took the snapshot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization the snapshot belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The media store holding the rendered image', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.mediastore'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system whose axes are this matrix's two enumerations. Owned by the dataset, and the space a FIELD edge lands in", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this sparse dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The folder this sparse dataset is filed in. Organisational only -- it says nothing about what its axes are or where they point', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this sparse dataset belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this table's coordinate columns are expressed in. Its axes are derived from those columns, so there is no second copy that can disagree", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this table dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The folder this table dataset is filed in. Organisational only -- it says nothing about where the rows sit in space', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this table dataset belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Parquet store holding the rows. The client reads it directly with a datalayer access grant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.parquetstore'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this transformation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='field',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(FIELD) The coordinate system of the array whose values are this map, when that array is a separate one (a warp field). Null when the input is its own field, as for a label mask whose pixels are the map. Its value axis (COORDINATE or DISPLACEMENT) says whether the values are positions or offsets; no value axis means scalar, and scalar means positions', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='input',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The coordinate system this transformation maps from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this transformation belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='output',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The coordinate system this transformation maps to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='layer',
            name='annotation_collection',
            field=models.ForeignKey(blank=True, help_text='(annotation) The annotation collection, owning its own coordinate system, whose drawn shapes this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.annotationcollection'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.layer'),
        ),
        migrations.AddField(
            model_name='lens',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this lens' voxels are expressed in. An unsliced lens shares its dataset's; a sliced one has its own, with a stored edge carrying the shift", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lenses', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='lens',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='core.arraydataset'),
        ),
        migrations.AddField(
            model_name='layer',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='(image) The lens that defines the array data source and constraints', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.lens'),
        ),
        migrations.AddField(
            model_name='historicallens',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.lens'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='lens',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(image) The lens that defines the array data source and constraints', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lens'),
        ),
        migrations.AddField(
            model_name='lightpath',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='light_graph', to='core.coordinateanchor'),
        ),
        migrations.AddField(
            model_name='meshcollection',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this collection's vertices are expressed in. An edge relates it to whatever the meshes were extracted from -- an identity when the grids agree, a scale when they do not", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesh_collections', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='meshcollection',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user that created this mesh collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meshcollection',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='The folder this mesh collection is filed in. Organisational only -- it says nothing about where the meshes sit in space', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesh_collections', to='core.folder'),
        ),
        migrations.AddField(
            model_name='meshcollection',
            name='organization',
            field=models.ForeignKey(help_text='The organization this mesh collection belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='meshcollection',
            name='store',
            field=models.ForeignKey(help_text='The fabriks store holding this collection: one prefix with its manifest, both catalogs and every octree level. Its manifest is where the grid and the encoding come from', on_delete=django.db.models.deletion.CASCADE, related_name='mesh_collections', to='datalayer.fabriksstore'),
        ),
        migrations.AddField(
            model_name='layer',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, help_text='(mesh) The versioned mesh collection, owning its own coordinate system, that this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh_layers', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='historicalmeshcollection',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(mesh) The versioned mesh collection, owning its own coordinate system, that this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(MESH_COLLECTION) The mesh collection side of the link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='mesh_collection',
            field=models.ForeignKey(blank=True, help_text='(MESH_COLLECTION) The mesh collection side of the link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='core.meshcollection'),
        ),
        migrations.AddField(
            model_name='metaschema',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalmetaschema',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.metaschema'),
        ),
        migrations.AddField(
            model_name='omemetadata',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ome_metadata', to='core.coordinateanchor'),
        ),
        migrations.AddField(
            model_name='optikitstate',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microscope', to='core.coordinateanchor'),
        ),
        migrations.AddField(
            model_name='phasorcalibration',
            name='anchor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phasor_calibrations', to='core.coordinateanchor'),
        ),
        migrations.AddField(
            model_name='phasorhistogram',
            name='anchor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phasor_histograms', to='core.coordinateanchor'),
        ),
        migrations.AddField(
            model_name='scene',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='scene',
            name='world',
            field=models.ForeignKey(help_text="The space this scene composes its layers over: a shared world system created for convenience alongside the scene, or an adopted existing system -- a shared space, a dataset's intrinsic grid, a physical space, a collection's space. Never owned by the scene: many scenes can share it, it outlives each of them, and deleting a scene never deletes it. RESTRICT: while a scene is rooted in a space, neither the space nor its owning container can be deleted", on_delete=django.db.models.deletion.RESTRICT, related_name='scenes', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='layer',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.scene'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='scene',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The composition this is a picture of', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene'),
        ),
        migrations.AddField(
            model_name='historicalscene',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.scene'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='scene',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene'),
        ),
        migrations.AddField(
            model_name='historicalarraydataset',
            name='default_scene',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The scene to open for this dataset, and the one its thumbnail is taken from. Bookkeeping only: it claims nothing about where the data sits and is not an answer to which scenes *show* this dataset -- that is `scenes`, a question the coordinate graph answers. Several datasets may nominate one scene. Cleared, not cascaded, when the scene is deleted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene'),
        ),
        migrations.AddField(
            model_name='historicalannotationcollection',
            name='scene',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The scene this collection was minted for as its default drawing surface, if any. One per scene; bookkeeping only, placement is the registration edge', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene'),
        ),
        migrations.AddField(
            model_name='historicalanimation',
            name='scene',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The scene this tour flies through', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.scene'),
        ),
        migrations.AddField(
            model_name='arraydataset',
            name='default_scene',
            field=models.ForeignKey(blank=True, help_text='The scene to open for this dataset, and the one its thumbnail is taken from. Bookkeeping only: it claims nothing about where the data sits and is not an answer to which scenes *show* this dataset -- that is `scenes`, a question the coordinate graph answers. Several datasets may nominate one scene. Cleared, not cascaded, when the scene is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='core.scene'),
        ),
        migrations.AddField(
            model_name='annotationcollection',
            name='scene',
            field=models.OneToOneField(blank=True, help_text='The scene this collection was minted for as its default drawing surface, if any. One per scene; bookkeeping only, placement is the registration edge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_collection', to='core.scene'),
        ),
        migrations.AddField(
            model_name='animation',
            name='scene',
            field=models.ForeignKey(help_text='The scene this tour flies through', on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='core.scene'),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user that took the snapshot', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='organization',
            field=models.ForeignKey(help_text='The organization the snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the snapshot', related_name='pinned_scene_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='scene',
            field=models.ForeignKey(help_text='The composition this is a picture of', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.scene'),
        ),
        migrations.AddField(
            model_name='scenesnapshot',
            name='store',
            field=models.ForeignKey(help_text='The media store holding the rendered image', on_delete=django.db.models.deletion.CASCADE, related_name='scene_snapshots', to='datalayer.mediastore'),
        ),
        migrations.AddField(
            model_name='historicalscenesnapshot',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.scenesnapshot'),
        ),
        migrations.AddField(
            model_name='sparsearray',
            name='store',
            field=models.ForeignKey(help_text='The store holding this layout. Its spec, shape and per-layout chunking were read from the artifact when its upload was finished. Both layouts of one matrix share it', on_delete=django.db.models.deletion.CASCADE, related_name='sparse_arrays', to='datalayer.sparsestore'),
        ),
        migrations.AddField(
            model_name='sparsedataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system whose axes are this matrix's two enumerations. Owned by the dataset, and the space a FIELD edge lands in", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sparse_datasets', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='sparsedataset',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='sparsedataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sparsedataset',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user that created this sparse dataset', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sparsedataset',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='The folder this sparse dataset is filed in. Organisational only -- it says nothing about what its axes are or where they point', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparse_datasets', to='core.folder'),
        ),
        migrations.AddField(
            model_name='sparsedataset',
            name='organization',
            field=models.ForeignKey(help_text='The organization this sparse dataset belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='sparseaxisreference',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_references', to='core.sparsedataset'),
        ),
        migrations.AddField(
            model_name='sparsearray',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrays', to='core.sparsedataset'),
        ),
        migrations.AddField(
            model_name='historicalsparsedataset',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.sparsedataset'),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='coordinate_system',
            field=models.ForeignKey(blank=True, help_text="The coordinate system this table's coordinate columns are expressed in. Its axes are derived from those columns, so there is no second copy that can disagree", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_datasets', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user that created this table dataset', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='The folder this table dataset is filed in. Organisational only -- it says nothing about where the rows sit in space', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_datasets', to='core.folder'),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='organization',
            field=models.ForeignKey(help_text='The organization this table dataset belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='tabledataset',
            name='store',
            field=models.ForeignKey(help_text='The Parquet store holding the rows. The client reads it directly with a datalayer access grant', on_delete=django.db.models.deletion.CASCADE, related_name='table_datasets', to='datalayer.parquetstore'),
        ),
        migrations.AddField(
            model_name='sparseaxisreference',
            name='references',
            field=models.ForeignKey(help_text="The table whose rows this axis' positions are. Keyed by its single INDEX coordinate column, which is where a position is looked up -- the same contract `Column.references` carries", on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by_sparse_axes', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='layer',
            name='table_dataset',
            field=models.ForeignKey(blank=True, help_text='(point/track) The table dataset whose declared coordinate columns provide the coordinates; its own coordinate system is the space, and its column roles are the mapping -- nothing is duplicated per layer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='historicaltabledataset',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='table_dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(point/track) The table dataset whose declared coordinate columns provide the coordinates; its own coordinate system is the space, and its column roles are the mapping -- nothing is duplicated per layer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='historicalfilelink',
            name='table_dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(TABLE_DATASET) The table dataset side of the link', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='filelink',
            name='table_dataset',
            field=models.ForeignKey(blank=True, help_text='(TABLE_DATASET) The table dataset side of the link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='column',
            name='references',
            field=models.ForeignKey(blank=True, help_text="The table whose rows this column's values identify. Its declared schema says which column carries that identity (its single INDEX coordinate column); this FK states only *which table*, and the rest is derived. A data column may reference; so may an INDEX **coordinate** column, which is the product-space case -- its values are already ids, so naming the table it enumerates is what the enumeration is *of*. A SPACE or TIME coordinate may not: a position in nanometres and a row id are different things", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(help_text='The table dataset this column belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.tabledataset'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user that created this transformation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transformation',
            name='field',
            field=models.ForeignKey(blank=True, help_text='(FIELD) The coordinate system of the array whose values are this map, when that array is a separate one (a warp field). Null when the input is its own field, as for a label mask whose pixels are the map. Its value axis (COORDINATE or DISPLACEMENT) says whether the values are positions or offsets; no value axis means scalar, and scalar means positions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fields_of', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='input',
            field=models.ForeignKey(blank=True, help_text='The coordinate system this transformation maps from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='organization',
            field=models.ForeignKey(help_text='The organization this transformation belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='output',
            field=models.ForeignKey(blank=True, help_text='The coordinate system this transformation maps to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.coordinatesystem'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The wrapping SEQUENCE / BY_DIMENSION transformation, if this is a child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.transformation'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.transformation'),
        ),
        migrations.AddField(
            model_name='historicaltransformation',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The wrapping SEQUENCE / BY_DIMENSION transformation, if this is a child', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.transformation'),
        ),
        migrations.AddField(
            model_name='unstructuredmeta',
            name='file',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unstructured_metas', to='core.file'),
        ),
        migrations.AddField(
            model_name='unstructuredmeta',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metaschema'),
        ),
        migrations.AddField(
            model_name='valuehistogram',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value_histogram', to='core.coordinateanchor'),
        ),
        migrations.AddConstraint(
            model_name='animationwaypoint',
            constraint=models.UniqueConstraint(fields=('animation', 'order'), name='unique_animation_waypoint_order'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['coordinates'], name='annotation_coords_gin'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['bbox_cube'], name='annotation_bbox_gist'),
        ),
        migrations.AddIndex(
            model_name='coordinateanchor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['coordinates'], name='anchor_coords_gin'),
        ),
        migrations.AddConstraint(
            model_name='axis',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'TIME')), fields=('coordinate_system',), name='one_time_axis_per_coordinate_system'),
        ),
        migrations.AlterUniqueTogether(
            name='axis',
            unique_together={('coordinate_system', 'name'), ('coordinate_system', 'order')},
        ),
        migrations.AddConstraint(
            model_name='dataarray',
            constraint=models.UniqueConstraint(fields=('dataset', 'level'), name='one_data_array_per_level'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('creator', 'is_default', 'organization'), name='unique_default_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='only_one_folder_per_parent_and_name'),
        ),
        migrations.AddConstraint(
            model_name='phasorcalibration',
            constraint=models.UniqueConstraint(fields=('anchor', 'axis', 'harmonic'), name='unique_phasor_calibration'),
        ),
        migrations.AddConstraint(
            model_name='phasorhistogram',
            constraint=models.UniqueConstraint(fields=('anchor', 'axis', 'harmonic'), name='unique_phasor_histogram'),
        ),
        migrations.AddIndex(
            model_name='arraydataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['stored_spec'], name='array_dataset_spec_gin'),
        ),
        migrations.AddIndex(
            model_name='scenesnapshot',
            index=models.Index(fields=['scene', '-created_at'], name='scene_snapshot_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparsearray',
            constraint=models.UniqueConstraint(fields=('dataset', 'indexed_axis'), name='one_sparse_array_per_indexed_axis'),
        ),
        migrations.AddConstraint(
            model_name='sparseaxisreference',
            constraint=models.UniqueConstraint(fields=('dataset', 'axis'), name='one_reference_per_sparse_axis'),
        ),
        migrations.AddConstraint(
            model_name='filelink',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset__isnull', False)), fields=('file', 'dataset', 'direction', 'series_identifier'), name='unique_file_link_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='filelink',
            constraint=models.UniqueConstraint(condition=models.Q(('table_dataset__isnull', False)), fields=('file', 'table_dataset', 'direction', 'series_identifier'), name='unique_file_link_per_table_dataset'),
        ),
        migrations.AddConstraint(
            model_name='filelink',
            constraint=models.UniqueConstraint(condition=models.Q(('mesh_collection__isnull', False)), fields=('file', 'mesh_collection', 'direction', 'series_identifier'), name='unique_file_link_per_mesh_collection'),
        ),
        migrations.AddConstraint(
            model_name='filelink',
            constraint=models.UniqueConstraint(condition=models.Q(('annotation_collection__isnull', False)), fields=('file', 'annotation_collection', 'direction', 'series_identifier'), name='unique_file_link_per_annotation_collection'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='unique_table_column_name'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('table', 'order'), name='unique_table_column_order'),
        ),
    ]
