# Generated by Django 6.0.6 on 2026-08-26 14:59

import core.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='blue_index',
            field=models.IntegerField(blank=True, help_text='(rgb) The index along the intensity axis carrying the blue component', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='clim_max',
            field=models.FloatField(blank=True, help_text="(intensity/rgb) Upper contrast limit, in the data's own intensity units -- not a normalized fraction", null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='clim_min',
            field=models.FloatField(blank=True, help_text="(intensity/rgb) Lower contrast limit, in the data's own intensity units -- not a normalized fraction. RGB shares one pair across all three channels, because they are components of one picture rather than three signals", null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='gamma',
            field=models.FloatField(blank=True, help_text='(intensity) Gamma correction applied to the normalized intensities', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='green_index',
            field=models.IntegerField(blank=True, help_text='(rgb) The index along the intensity axis carrying the green component', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='intensity_axis',
            field=models.CharField(blank=True, help_text='(intensity/rgb) The lens axis carrying the channels, or null when the pixel value itself is the intensity (a single-valued volume)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='intensity_index',
            field=models.IntegerField(blank=True, help_text='(intensity) The index along the intensity axis to render', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='name',
            field=models.CharField(blank=True, help_text="A human-readable name for the layer, e.g. the channel it draws ('DAPI'). Null when nobody has named it", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='phasor_render',
            field=models.JSONField(blank=True, default=None, help_text='(phasor) Which axis is reduced to a phasor, at which harmonic, and how the resulting (g, s) becomes color. The single source of truth for how the phasor layer is rendered.', null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='projection_mode',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('mip', 'Maximum intensity projection'), ('attenuated_mip', 'Attenuated maximum intensity projection'), ('volume', 'Alpha volume rendering'), ('isosurface', 'Isosurface')], choices_enum=core.enums.ProjectionModeChoices, default=None, help_text='(intensity) How z is collapsed. Null means draw the plane; set means project over z', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='red_index',
            field=models.IntegerField(blank=True, help_text='(rgb) The index along the intensity axis carrying the red component', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='blue_index',
            field=models.IntegerField(blank=True, help_text='(rgb) The index along the intensity axis carrying the blue component', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='clim_max',
            field=models.FloatField(blank=True, help_text="(intensity/rgb) Upper contrast limit, in the data's own intensity units -- not a normalized fraction", null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='clim_min',
            field=models.FloatField(blank=True, help_text="(intensity/rgb) Lower contrast limit, in the data's own intensity units -- not a normalized fraction. RGB shares one pair across all three channels, because they are components of one picture rather than three signals", null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='gamma',
            field=models.FloatField(blank=True, help_text='(intensity) Gamma correction applied to the normalized intensities', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='green_index',
            field=models.IntegerField(blank=True, help_text='(rgb) The index along the intensity axis carrying the green component', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='intensity_axis',
            field=models.CharField(blank=True, help_text='(intensity/rgb) The lens axis carrying the channels, or null when the pixel value itself is the intensity (a single-valued volume)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='intensity_index',
            field=models.IntegerField(blank=True, help_text='(intensity) The index along the intensity axis to render', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='name',
            field=models.CharField(blank=True, help_text="A human-readable name for the layer, e.g. the channel it draws ('DAPI'). Null when nobody has named it", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='phasor_render',
            field=models.JSONField(blank=True, default=None, help_text='(phasor) Which axis is reduced to a phasor, at which harmonic, and how the resulting (g, s) becomes color. The single source of truth for how the phasor layer is rendered.', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='projection_mode',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('mip', 'Maximum intensity projection'), ('attenuated_mip', 'Attenuated maximum intensity projection'), ('volume', 'Alpha volume rendering'), ('isosurface', 'Isosurface')], choices_enum=core.enums.ProjectionModeChoices, default=None, help_text='(intensity) How z is collapsed. Null means draw the plane; set means project over z', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='red_index',
            field=models.IntegerField(blank=True, help_text='(rgb) The index along the intensity axis carrying the red component', null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='colormap',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('viridis', 'Viridis'), ('plasma', 'Plasma'), ('inferno', 'Inferno'), ('magma', 'Magma'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('rainbow', 'Rainbow'), ('spectral', 'Spectral'), ('cool', 'Cool'), ('warm', 'Warm'), ('intensity', 'Intensity'), ('hues', 'Hues'), ('distinct', 'Distinct'), ('pastel', 'Pastel'), ('vivid', 'Vivid')], choices_enum=core.enums.ColorMapChoices, default=None, help_text='(intensity/point/track) The applying color map', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicallayer',
            name='lens',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(image/intensity/rgb/phasor/label) The lens that defines the array data source and constraints', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lens'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='colormap',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('viridis', 'Viridis'), ('plasma', 'Plasma'), ('inferno', 'Inferno'), ('magma', 'Magma'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('rainbow', 'Rainbow'), ('spectral', 'Spectral'), ('cool', 'Cool'), ('warm', 'Warm'), ('intensity', 'Intensity'), ('hues', 'Hues'), ('distinct', 'Distinct'), ('pastel', 'Pastel'), ('vivid', 'Vivid')], choices_enum=core.enums.ColorMapChoices, default=None, help_text='(intensity/point/track) The applying color map', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lens',
            field=models.ForeignKey(blank=True, help_text='(image/intensity/rgb/phasor/label) The lens that defines the array data source and constraints', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.lens'),
        ),
    ]
