# Generated by Django 6.0.6 on 2026-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flatten_single_source_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='color',
            field=models.JSONField(blank=True, default=None, help_text='(intensity) A solid RGBA color to tint the channel with, instead of a colormap: four components, each 0..255', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='color',
            field=models.JSONField(blank=True, default=None, help_text='(intensity) A solid RGBA color to tint the channel with, instead of a colormap: four components, each 0..255', null=True),
        ),
    ]
