# Generated by Django 6.0.6 on 2026-08-31 09:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0005_intensity_layer_tint'),
        ('datalayer', '0002_konnektionstore'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="The immutable version of this collection, e.g. 'v20260713-a3f9'", max_length=64)),
                ('spec_version', models.CharField(help_text='The version of the network encoding specification this collection conforms to', max_length=64)),
                ('grid', models.JSONField(default=dict, help_text="The octree grid, as read from the store's manifest: {'cellSize': [128, 128, 64], 'levels': 1, 'sortKey': 'MORTON'}. cellSize is in voxels, one size per position component. `levels: 1` is the common case, not a degenerate one")),
                ('encoding', models.JSONField(default=dict, help_text="The geometry encoding, as read from the store's manifest: how positions, edges, node ids, radii and ghosts are packed, and which coarsening operations ran")),
                ('provenance_metadata', models.JSONField(default=dict, help_text='How this collection was produced (the tracing run, its parameters and its inputs)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this network collection was created')),
                ('coordinate_system', models.ForeignKey(blank=True, help_text="The coordinate system this collection's node positions are expressed in. An edge relates it to whatever the network was traced out of", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_collections', to='core.coordinatesystem')),
                ('creator', models.ForeignKey(blank=True, help_text='The user that created this network collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, help_text='The folder this network collection is filed in. Organisational only -- it says nothing about where the networks sit in space', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_collections', to='core.folder')),
                ('organization', models.ForeignKey(help_text='The organization this network collection belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('store', models.ForeignKey(help_text='The konnektion store holding this collection: one prefix with its manifest, both catalogs and every octree level. Its manifest is where the grid and the encoding come from', on_delete=django.db.models.deletion.CASCADE, related_name='network_collections', to='datalayer.konnektionstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNetworkCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.CharField(help_text="The immutable version of this collection, e.g. 'v20260713-a3f9'", max_length=64)),
                ('spec_version', models.CharField(help_text='The version of the network encoding specification this collection conforms to', max_length=64)),
                ('grid', models.JSONField(default=dict, help_text="The octree grid, as read from the store's manifest: {'cellSize': [128, 128, 64], 'levels': 1, 'sortKey': 'MORTON'}. cellSize is in voxels, one size per position component. `levels: 1` is the common case, not a degenerate one")),
                ('encoding', models.JSONField(default=dict, help_text="The geometry encoding, as read from the store's manifest: how positions, edges, node ids, radii and ghosts are packed, and which coarsening operations ran")),
                ('provenance_metadata', models.JSONField(default=dict, help_text='How this collection was produced (the tracing run, its parameters and its inputs)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this network collection was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('coordinate_system', models.ForeignKey(blank=True, db_constraint=False, help_text="The coordinate system this collection's node positions are expressed in. An edge relates it to whatever the network was traced out of", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this network collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, db_constraint=False, help_text='The folder this network collection is filed in. Organisational only -- it says nothing about where the networks sit in space', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.folder')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, help_text='The organization this network collection belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('store', models.ForeignKey(blank=True, db_constraint=False, help_text='The konnektion store holding this collection: one prefix with its manifest, both catalogs and every octree level. Its manifest is where the grid and the encoding come from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.konnektionstore')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.networkcollection')),
            ],
            options={
                'verbose_name': 'historical network collection',
                'verbose_name_plural': 'historical network collections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
