# Generated by Django 6.0.6 on 2026-08-31 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_networkcollection_historicalnetworkcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='directed',
            field=models.BooleanField(default=False, help_text='(network) Whether to draw the edge direction, e.g. as arrowheads. The data is always ordered source-to-target; this is a render setting, not a fact about the graph'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='edge_width_column',
            field=models.CharField(blank=True, help_text='(network) The per-edge column giving each segment a uniform width. Ignored when `nodeSizeColumn` is set, which is the more specific statement', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='network_collection',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(network) The versioned network collection, owning its own coordinate system, that this layer renders', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.networkcollection'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='node_size_column',
            field=models.CharField(blank=True, help_text="(network) The per-node column giving each node's radius, so a segment tapers between its endpoints. Read from the collection's attributes, in scene units", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='show_nodes',
            field=models.BooleanField(default=False, help_text='(network) Whether to draw a glyph at each node as well as the segments between them. Useful for a sparse graph, noise on a dense arbor'),
        ),
        migrations.AddField(
            model_name='layer',
            name='directed',
            field=models.BooleanField(default=False, help_text='(network) Whether to draw the edge direction, e.g. as arrowheads. The data is always ordered source-to-target; this is a render setting, not a fact about the graph'),
        ),
        migrations.AddField(
            model_name='layer',
            name='edge_width_column',
            field=models.CharField(blank=True, help_text='(network) The per-edge column giving each segment a uniform width. Ignored when `nodeSizeColumn` is set, which is the more specific statement', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='network_collection',
            field=models.ForeignKey(blank=True, help_text='(network) The versioned network collection, owning its own coordinate system, that this layer renders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_layers', to='core.networkcollection'),
        ),
        migrations.AddField(
            model_name='layer',
            name='node_size_column',
            field=models.CharField(blank=True, help_text="(network) The per-node column giving each node's radius, so a segment tapers between its endpoints. Read from the collection's attributes, in scene units", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='show_nodes',
            field=models.BooleanField(default=False, help_text='(network) Whether to draw a glyph at each node as well as the segments between them. Useful for a sparse graph, noise on a dense arbor'),
        ),
    ]
