# Generated by Django 6.0.6 on 2026-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicallayer_directed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='network_color_bys',
            field=models.JSONField(blank=True, default=list, help_text='(network) The colourings this layer offers, in the order a picker should show them. Each colours objects by a table column or sparse slice their ids reach, or nodes by a per-node attribute the collection itself carries. Empty means the flat material color is the only rendering'),
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='network_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text='(network) The filters this layer offers, in the order a picker should show them. Each keeps or drops objects by a reachable table column or sparse slice, or nodes and segments by a per-node attribute the collection carries. Empty means nothing is offered and everything draws'),
        ),
        migrations.AddField(
            model_name='layer',
            name='network_color_bys',
            field=models.JSONField(blank=True, default=list, help_text='(network) The colourings this layer offers, in the order a picker should show them. Each colours objects by a table column or sparse slice their ids reach, or nodes by a per-node attribute the collection itself carries. Empty means the flat material color is the only rendering'),
        ),
        migrations.AddField(
            model_name='layer',
            name='network_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text='(network) The filters this layer offers, in the order a picker should show them. Each keeps or drops objects by a reachable table column or sparse slice, or nodes and segments by a per-node attribute the collection carries. Empty means nothing is offered and everything draws'),
        ),
    ]
