# Generated by Django 6.0.6 on 2026-08-31 15:02

import core.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_historicallayer_network_color_bys_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallayer",
            name="glyph",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("arrow", "Arrow (a shaft with a head)"),
                    ("line", "Line (a bare segment, direction unmarked)"),
                    ("cone", "Cone (a solid cone pointing along the vector)"),
                ],
                choices_enum=core.enums.VectorGlyphChoices,
                default="arrow",
                help_text="(vector) How one sampled vector is drawn: an arrow, a bare line, or a cone. Always triangle geometry, never a sprite -- a sprite is not an occluder in a volume pass",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="historicallayer",
            name="glyph_scale",
            field=models.FloatField(
                blank=True,
                help_text="(vector) How a magnitude becomes a drawn length: scene units per unit of the component axis. Null auto-normalizes to the sampled maximum. In scene units, so like `point_size` it is well defined for a layer only when its `placementInvariance` is SIMILARITY or better (RFC-8)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallayer",
            name="glyph_stride",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="(vector) Sample every Nth voxel per spatial axis. Null lets the renderer pick a stride from its own glyph budget -- a dense field at full resolution is millions of glyphs, which is a picture of overdraw rather than of flow",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="glyph",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("arrow", "Arrow (a shaft with a head)"),
                    ("line", "Line (a bare segment, direction unmarked)"),
                    ("cone", "Cone (a solid cone pointing along the vector)"),
                ],
                choices_enum=core.enums.VectorGlyphChoices,
                default="arrow",
                help_text="(vector) How one sampled vector is drawn: an arrow, a bare line, or a cone. Always triangle geometry, never a sprite -- a sprite is not an occluder in a volume pass",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="glyph_scale",
            field=models.FloatField(
                blank=True,
                help_text="(vector) How a magnitude becomes a drawn length: scene units per unit of the component axis. Null auto-normalizes to the sampled maximum. In scene units, so like `point_size` it is well defined for a layer only when its `placementInvariance` is SIMILARITY or better (RFC-8)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="glyph_stride",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="(vector) Sample every Nth voxel per spatial axis. Null lets the renderer pick a stride from its own glyph budget -- a dense field at full resolution is millions of glyphs, which is a picture of overdraw rather than of flow",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallayer",
            name="clim_max",
            field=models.FloatField(
                blank=True,
                help_text="(intensity/rgb/vector) Upper contrast limit, in the data's own units -- not a normalized fraction. For a vector layer: vector magnitude, in the component axis's unit",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallayer",
            name="clim_min",
            field=models.FloatField(
                blank=True,
                help_text="(intensity/rgb/vector) Lower contrast limit, in the data's own units -- not a normalized fraction. For intensity and RGB that means intensity units (RGB shares one pair across all three channels, because they are components of one picture rather than three signals); for a vector layer it means vector MAGNITUDE, in the component axis's unit -- the two readings share this column, so both are stated here rather than left to collide",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallayer",
            name="color",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="(intensity/vector) A solid RGBA color instead of a colormap: four components, each 0..255. For intensity, a tint over the channel; for a vector layer, a flat glyph colour where a magnitude ramp is noise",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallayer",
            name="colormap",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("viridis", "Viridis"),
                    ("plasma", "Plasma"),
                    ("inferno", "Inferno"),
                    ("magma", "Magma"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("cyan", "Cyan"),
                    ("magenta", "Magenta"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                    ("white", "White"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("grey", "Grey"),
                    ("rainbow", "Rainbow"),
                    ("spectral", "Spectral"),
                    ("cool", "Cool"),
                    ("warm", "Warm"),
                    ("intensity", "Intensity"),
                    ("hues", "Hues"),
                    ("distinct", "Distinct"),
                    ("pastel", "Pastel"),
                    ("vivid", "Vivid"),
                ],
                choices_enum=core.enums.ColorMapChoices,
                default=None,
                help_text="(intensity/point/track/vector) The applying color map. A vector layer applies it over glyph magnitude",
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallayer",
            name="lens",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="(image/intensity/rgb/phasor/label/vector) The lens that defines the array data source and constraints",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.lens",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="clim_max",
            field=models.FloatField(
                blank=True,
                help_text="(intensity/rgb/vector) Upper contrast limit, in the data's own units -- not a normalized fraction. For a vector layer: vector magnitude, in the component axis's unit",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="clim_min",
            field=models.FloatField(
                blank=True,
                help_text="(intensity/rgb/vector) Lower contrast limit, in the data's own units -- not a normalized fraction. For intensity and RGB that means intensity units (RGB shares one pair across all three channels, because they are components of one picture rather than three signals); for a vector layer it means vector MAGNITUDE, in the component axis's unit -- the two readings share this column, so both are stated here rather than left to collide",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="color",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="(intensity/vector) A solid RGBA color instead of a colormap: four components, each 0..255. For intensity, a tint over the channel; for a vector layer, a flat glyph colour where a magnitude ramp is noise",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="colormap",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("viridis", "Viridis"),
                    ("plasma", "Plasma"),
                    ("inferno", "Inferno"),
                    ("magma", "Magma"),
                    ("red", "Red"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("cyan", "Cyan"),
                    ("magenta", "Magenta"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                    ("white", "White"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("brown", "Brown"),
                    ("grey", "Grey"),
                    ("rainbow", "Rainbow"),
                    ("spectral", "Spectral"),
                    ("cool", "Cool"),
                    ("warm", "Warm"),
                    ("intensity", "Intensity"),
                    ("hues", "Hues"),
                    ("distinct", "Distinct"),
                    ("pastel", "Pastel"),
                    ("vivid", "Vivid"),
                ],
                choices_enum=core.enums.ColorMapChoices,
                default=None,
                help_text="(intensity/point/track/vector) The applying color map. A vector layer applies it over glyph magnitude",
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="lens",
            field=models.ForeignKey(
                blank=True,
                help_text="(image/intensity/rgb/phasor/label/vector) The lens that defines the array data source and constraints",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layers",
                to="core.lens",
            ),
        ),
    ]
