# Generated by Django 6.0.6 on 2026-08-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_vector_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="node_references",
            field=models.ForeignKey(
                blank=True,
                help_text="The network collection whose NODE ids this INDEX coordinate column's values are, scoped by a sibling INDEX axis keyed by the same collection's object ids (a node id is unique only within its traced object, so the pair is the row's key). One such column makes the table per-node; two over one collection are its edges' (source, target), in axis declaration order. PROTECT for the reason `references` is: deleting the collection would orphan the meaning of every value in the column",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="node_referenced_by",
                to="core.networkcollection",
            ),
        ),
    ]
