# Generated by Django 6.0.6 on 2026-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unnest_cross_org_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallayer',
            name='white_balance',
            field=models.JSONField(blank=True, default=None, help_text='(rgb) Per-component gains [red, green, blue], each > 0, multiplied into the components before the shared contrast limits. Null: no correction, the same as [1, 1, 1]', null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='white_balance',
            field=models.JSONField(blank=True, default=None, help_text='(rgb) Per-component gains [red, green, blue], each > 0, multiplied into the components before the shared contrast limits. Null: no correction, the same as [1, 1, 1]', null=True),
        ),
    ]
