# Generated by Django 3.1.7 on 2021-02-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representation',
            options={'permissions': [('download_representation', 'Can download Presentation')]},
        ),
        migrations.AlterModelOptions(
            name='roi',
            options={},
        ),
        migrations.AlterField(
            model_name='representation',
            name='variety',
            field=models.CharField(choices=[('MASK', 'Mask (Value represent Labels)'), ('VOXEL', 'Voxel (Value represent Intensity)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='The Representation can have varying types, consult your API', max_length=400),
        ),
    ]
