# Generated by Django 3.2 on 2021-04-16 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grunnlag.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(grunnlag.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grunnlag.experiment'),
        ),
        migrations.AddField(
            model_name='sample',
            name='experimentalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grunnlag.experimentalgroup'),
        ),
        migrations.AddField(
            model_name='roi',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roi',
            name='experimentalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grunnlag.experimentalgroup'),
        ),
        migrations.AddField(
            model_name='roi',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='grunnlag.representation'),
        ),
        migrations.AddField(
            model_name='representation',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived', related_query_name='derived', to='grunnlag.representation'),
        ),
        migrations.AddField(
            model_name='representation',
            name='sample',
            field=models.ForeignKey(help_text='The Sample this representation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='grunnlag.sample'),
        ),
        migrations.AddField(
            model_name='representation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='experimentalgroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentalgroup',
            name='experiment',
            field=models.ForeignKey(help_text='The experiment this Group belongs too', on_delete=django.db.models.deletion.CASCADE, to='grunnlag.experiment'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antibody',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grunnlag.experiment'),
        ),
        migrations.AddField(
            model_name='animal',
            name='experimentalgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grunnlag.experimentalgroup'),
        ),
    ]
