# Generated by Django 3.2.16 on 2023-01-27 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='physical_size',
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_size',
            field=models.JSONField(default={}, help_text='The physical size of a position vector unit in micrometer'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='shape',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='The arrays shape format [c,t,z,y,x]', null=True, size=None),
        ),
    ]
