# Generated by Django 3.2.19 on 2023-05-04 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('lok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('grunnlag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_while', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(help_text='The name of the era', max_length=1000)),
                ('start', models.DateTimeField(help_text='The start of the era')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='era_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_through', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='era_created_through', to='lok.lokclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_while', models.CharField(blank=True, max_length=1000, null=True)),
                ('delta_t', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timepoint_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_through', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timepoint_created_through', to='lok.lokclient')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timepoints', to='grunnlag.era')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that have pinned the position', related_name='pinned_timepoints', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='omero',
            name='timepoints',
            field=models.ManyToManyField(related_name='omeros', to='grunnlag.Timepoint'),
        ),
        migrations.AddConstraint(
            model_name='timepoint',
            constraint=models.UniqueConstraint(fields=('era', 'delta_t'), name='Only one unique timepoint per era'),
        ),
    ]
