# Generated by Django 3.2.10 on 2022-02-10 10:25

from django.db import migrations, models
import grunnlag.models
import grunnlag.storage


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omerofile',
            name='file',
            field=grunnlag.models.OmeroFileField(blank=True, null=True, storage=grunnlag.storage.PrivateMediaStorage(), upload_to='files'),
        ),
        migrations.AlterField(
            model_name='roi',
            name='vectors',
            field=models.JSONField(default=list, help_text='A json dump of the ROI Vectors (specific for each type)', max_length=3000),
        ),
    ]
