# Generated by Django 3.2.8 on 2021-11-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmeroMetaRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_sizes', models.JSONField(default={'t': 1, 'x': 1, 'y': 1, 'z': 1})),
                ('channels', models.JSONField(default=['name', 'emmission_wavelength', 'excitation_wavelength', 'acquistion_mode', 'color'])),
                ('planes', models.JSONField(default=['z_index', 'y_index', 'x_index', 'c_index', 't_index', 'exposure_time', 'delta_t'])),
            ],
        ),
        migrations.AddField(
            model_name='representation',
            name='omero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grunnlag.omerometarepresentation'),
        ),
    ]
