# Generated by Django 3.2.10 on 2022-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0002_auto_20220210_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='type',
            field=models.CharField(choices=[('Ellipsis', 'Elipsis'), ('Box', 'Box')], default='Box', help_text='The Representation can have varying types, consult your API', max_length=400),
        ),
    ]
