# Generated by Django 3.2 on 2021-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='experiment',
        ),
        migrations.AddField(
            model_name='sample',
            name='experiment',
            field=models.ManyToManyField(blank=True, null=True, to='grunnlag.Experiment'),
        ),
    ]
