# Generated by Django 3.2.19 on 2023-05-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0002_auto_20230504_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepoint',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the timepoint', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='timepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='grunnlag.timepoint'),
        ),
    ]
