# Generated by Django 3.2.16 on 2022-12-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0002_auto_20221209_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'permissions': [('download_representation', 'Can download Presentation')]},
        ),
        migrations.AlterField(
            model_name='omero',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omeros', to='grunnlag.instrument'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('stage', 'x', 'y', 'z'), name='Only one unique posistion per stage'),
        ),
    ]
