# Generated by Django 3.2.16 on 2023-01-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0002_auto_20230127_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stage_size',
        ),
    ]
