# Generated by Django 3.2.8 on 2021-11-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0002_auto_20211103_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omerometarepresentation',
            old_name='physical_sizes',
            new_name='physical_size',
        ),
    ]
