# Generated by Django 3.2.19 on 2023-05-04 10:18

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('grunnlag', '0003_auto_20230504_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='era',
            name='end',
            field=models.DateTimeField(blank=True, help_text='The end of the era', null=True),
        ),
        migrations.AddField(
            model_name='era',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that have pinned the era', related_name='pinned_eras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='era',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='era',
            name='start',
            field=models.DateTimeField(blank=True, help_text='The start of the era', null=True),
        ),
    ]
