# Generated by Django 3.2 on 2021-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0003_auto_20210504_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='experiment',
        ),
        migrations.AddField(
            model_name='sample',
            name='experiments',
            field=models.ManyToManyField(blank=True, null=True, related_name='samples', to='grunnlag.Experiment'),
        ),
    ]
