# Generated by Django 3.2.10 on 2022-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0003_roi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='type',
            field=models.CharField(choices=[('ellipse', 'Ellipse'), ('polygon', 'POLYGON'), ('line', 'Line'), ('rectangle', 'Rectangle'), ('path', 'Path'), ('unknown', 'Unknown')], default='unknown', help_text='The Representation can have varying types, consult your API', max_length=400),
        ),
    ]
