# Generated by Django 3.2.8 on 2021-11-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0003_rename_physical_sizes_omerometarepresentation_physical_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='omero',
        ),
        migrations.DeleteModel(
            name='OmeroMetaRepresentation',
        ),
    ]
