# Generated by Django 3.2.10 on 2022-02-10 15:48

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('grunnlag', '0004_alter_roi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='variety',
            field=models.CharField(choices=[('MASK', 'Mask (Value represent Labels)'), ('VOXEL', 'Voxel (Value represent Intensity)'), ('RGB', 'RGB (First three channel represent RGB)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='The Representation can have varying types, consult your API', max_length=400),
        ),
    ]
