# Generated by Django 3.2.19 on 2023-05-04 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0004_auto_20230504_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='era',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time the experiment was created'),
            preserve_default=False,
        ),
    ]
