# Generated by Django 3.2.16 on 2023-02-07 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0004_omero_affine_transformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the experiment', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_through', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_created_through', to='lok.lokclient')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='grunnlag.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='context',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context', to='grunnlag.dataset'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='grunnlag.dataset'),
        ),
        migrations.AddField(
            model_name='model',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='grunnlag.dataset'),
        ),
        migrations.AddField(
            model_name='omerofile',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='omerofile', to='grunnlag.dataset'),
        ),
        migrations.AddField(
            model_name='representation',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representation', to='grunnlag.dataset'),
        ),
        migrations.AddField(
            model_name='sample',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='grunnlag.dataset'),
        ),
        migrations.AddField(
            model_name='stage',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='grunnlag.dataset'),
        ),
    ]
