# Generated by Django 3.2.8 on 2021-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0004_auto_20211103_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='omeroa',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
