# Generated by Django 3.2 on 2021-05-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0004_auto_20210504_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='sample',
            field=models.ForeignKey(blank=True, help_text='The Sample this representation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='grunnlag.sample'),
        ),
    ]
