# Generated by Django 3.2.10 on 2022-03-23 14:31

import colorfield.fields
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lok', '0001_initial'),
        ('grunnlag', '0005_auto_20220210_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikroUser',
            fields=[
                ('lokuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lok.lokuser')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('lok.lokuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
