# Generated by Django 3.2.19 on 2023-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0006_timepoint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='roi_origins',
            field=models.ManyToManyField(related_name='derived_positions', to='grunnlag.ROI'),
        ),
    ]
