# Generated by Django 3.2.2 on 2021-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0006_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
