# Generated by Django 3.2.16 on 2023-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0006_dataset_pinned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='dataset',
        ),
        migrations.AddField(
            model_name='context',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='context', to='grunnlag.Dataset'),
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='dataset',
        ),
        migrations.AddField(
            model_name='experiment',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='experiment', to='grunnlag.Dataset'),
        ),
        migrations.RemoveField(
            model_name='model',
            name='dataset',
        ),
        migrations.AddField(
            model_name='model',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='model', to='grunnlag.Dataset'),
        ),
        migrations.RemoveField(
            model_name='omerofile',
            name='dataset',
        ),
        migrations.AddField(
            model_name='omerofile',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='omerofile', to='grunnlag.Dataset'),
        ),
        migrations.RemoveField(
            model_name='representation',
            name='dataset',
        ),
        migrations.AddField(
            model_name='representation',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='representation', to='grunnlag.Dataset'),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='dataset',
        ),
        migrations.AddField(
            model_name='sample',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='sample', to='grunnlag.Dataset'),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='dataset',
        ),
        migrations.AddField(
            model_name='stage',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='stage', to='grunnlag.Dataset'),
        ),
    ]
