# Generated by Django 3.2.9 on 2021-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0006_rename_omeroa_representation_omero'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmeroFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
