# Generated by Django 3.2.19 on 2023-05-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0007_position_roi_origins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_while', models.CharField(blank=True, max_length=1000, null=True)),
                ('serial_number', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('model', models.CharField(blank=True, max_length=1000, null=True)),
                ('bit_depth', models.IntegerField(blank=True, null=True)),
                ('sensor_size_x', models.FloatField(blank=True, null=True)),
                ('sensor_size_y', models.FloatField(blank=True, null=True)),
                ('sensor_size_unit', models.CharField(blank=True, max_length=1000, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_through', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_created_through', to='lok.lokclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='omero',
            name='cameras',
            field=models.ManyToManyField(related_name='omeros', to='grunnlag.Camera'),
        ),
    ]
