# Generated by Django 3.2.16 on 2023-02-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0007_auto_20230207_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RenameField(
            model_name='omerofile',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RenameField(
            model_name='representation',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='dataset',
            new_name='datasets',
        ),
    ]
