# Generated by Django 3.2.9 on 2021-11-16 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import grunnlag.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0007_omerofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='omerofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='omerofile',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='omerofile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=grunnlag.storage.PrivateMediaStorage(), upload_to='files'),
        ),
    ]
