# Generated by Django 3.2.9 on 2021-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0008_auto_20211116_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='omerofile',
            name='type',
            field=models.CharField(choices=[('TIF', 'Tiff'), ('MSR', 'MSR File'), ('CZI', 'Zeiss Microscopy File'), ('UNKNOWN', 'Unwknon File Format')], default='UNKNOWN', max_length=400),
        ),
    ]
