# Generated by Django 3.2.16 on 2023-02-07 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0008_auto_20230207_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time the experiment was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='context',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='contexts', to='grunnlag.Dataset'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='experiments', to='grunnlag.Dataset'),
        ),
        migrations.AlterField(
            model_name='model',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='models', to='grunnlag.Dataset'),
        ),
        migrations.AlterField(
            model_name='omerofile',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='omerofiles', to='grunnlag.Dataset'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='representations', to='grunnlag.Dataset'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='samples', to='grunnlag.Dataset'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='datasets',
            field=models.ManyToManyField(blank=True, null=True, related_name='stages', to='grunnlag.Dataset'),
        ),
    ]
