# Generated by Django 3.2.2 on 2021-05-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0009_representation_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representation',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
