# Generated by Django 3.2.2 on 2021-06-01 12:48

from django.conf import settings
from django.db import migrations, models
import grunnlag.models
import grunnlag.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0010_rename_image_representation_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(grunnlag.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='representation',
            name='thumbnail',
            field=models.ImageField(null=True, storage=grunnlag.storage.PrivateMediaStorage(), upload_to='thumbnails'),
        ),
    ]
