# Generated by Django 3.2.9 on 2021-11-22 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0010_alter_omerofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The Key', max_length=1000)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, help_text='The Representatoin this Metric belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='grunnlag.experiment')),
                ('rep', models.ForeignKey(blank=True, help_text='The Representatoin this Metric belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='grunnlag.representation')),
                ('sample', models.ForeignKey(blank=True, help_text='The Representatoin this Metric belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='grunnlag.sample')),
            ],
        ),
        migrations.DeleteModel(
            name='RepresentationMetric',
        ),
    ]
