# Generated by Django 3.2.16 on 2023-02-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0010_dataset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='immersion',
            field=models.CharField(default='oil', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='na',
            field=models.FloatField(default=0.3),
            preserve_default=False,
        ),
    ]
