# Generated by Django 3.2.10 on 2022-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0010_sizefeature_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
