# Generated by Django 3.2.9 on 2021-11-22 16:00

from django.db import migrations, models
import grunnlag.storage


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0011_auto_20211122_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(null=True, storage=grunnlag.storage.PrivateMediaStorage(), upload_to='thumbnails'),
        ),
    ]
