# Generated by Django 3.2.16 on 2023-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0011_auto_20230208_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='immersion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='magnification',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
