# Generated by Django 3.2.2 on 2021-06-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0011_auto_20210601_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representation',
            old_name='created_by',
            new_name='creator',
        ),
    ]
