# Generated by Django 3.2.14 on 2022-07-12 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grunnlag.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0012_omerofile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grunnlag.comment')),
                ('user', models.ForeignKey(on_delete=models.SET(grunnlag.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
