# Generated by Django 3.2.4 on 2021-07-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0013_auto_20210621_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='representation',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sample',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RepresentationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The Key', max_length=1000)),
                ('value', models.JSONField(default=dict)),
                ('rep', models.ForeignKey(help_text='The Representatoin this Metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='grunnlag.representation')),
            ],
        ),
    ]
