# Generated by Django 3.2.14 on 2022-07-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grunnlag.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='descendents',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='grunnlag.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(grunnlag.models.get_sentinel_user), related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
