# Generated by Django 3.2.4 on 2021-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0014_auto_20210721_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representation',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representationmetric',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
