# Generated by Django 3.2.14 on 2022-08-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0014_auto_20220712_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
