# Generated by Django 3.2.14 on 2022-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0015_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='representations', related_query_name='representations', to='grunnlag.OmeroFile'),
        ),
    ]
