# Generated by Django 3.2.4 on 2021-07-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0016_auto_20210721_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representationmetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
