# Generated by Django 3.2.14 on 2022-09-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0019_auto_20220906_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omero',
            name='representation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='omero', to='grunnlag.representation'),
        ),
    ]
