# Generated by Django 3.2.14 on 2022-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0020_alter_omero_representation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('key', 'label'), name='Only one unique key per label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('instance', 'representation'), name='Only one unique label per image'),
        ),
    ]
