# Generated by Django 3.2.14 on 2022-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0021_auto_20220920_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='major_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
