# Generated by Django 3.2.14 on 2022-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0023_auto_20220927_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='roi',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='roi',
            name='type',
            field=models.CharField(choices=[('ellipse', 'Ellipse'), ('polygon', 'POLYGON'), ('line', 'Line'), ('rectangle', 'Rectangle'), ('path', 'Path'), ('unknown', 'Unknown'), ('frame', 'Frame'), ('slice', 'Slice'), ('point', 'Point')], default='unknown', help_text='The Representation can have varying types, consult your API', max_length=400),
        ),
    ]
