# Generated by Django 3.2.14 on 2022-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0024_auto_20220927_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='rep',
            new_name='representation',
        ),
        migrations.RemoveField(
            model_name='representation',
            name='files',
        ),
        migrations.AddField(
            model_name='representation',
            name='file_origins',
            field=models.ManyToManyField(blank=True, null=True, related_name='derived_representations', related_query_name='derived_representations', to='grunnlag.OmeroFile'),
        ),
        migrations.AddField(
            model_name='representation',
            name='roi_origins',
            field=models.ManyToManyField(blank=True, null=True, related_name='derived_representations', related_query_name='derived_representations', to='grunnlag.ROI'),
        ),
    ]
