# Generated by Django 3.2.14 on 2022-09-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0025_auto_20220927_1510'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='Only one unique label per image',
        ),
        migrations.AlterField(
            model_name='representation',
            name='sample',
            field=models.ForeignKey(blank=True, help_text='The Sample this representation belosngs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='grunnlag.sample'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('instance', 'representation'), name='Only one unique label per images'),
        ),
    ]
