# Generated by Django 3.2.14 on 2022-09-28 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grunnlag', '0026_auto_20220927_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representation',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_representations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roi',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_rois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='representation',
            name='variety',
            field=models.CharField(choices=[('MASK', 'Mask (Value represent Labels)'), ('VOXEL', 'Voxel (Value represent Intensity)'), ('RGB', 'RGB (First three channel represent RGB)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='The Representation can have vasrying types, consult your API', max_length=400),
        ),
    ]
