# Generated by Django 3.2.16 on 2023-01-19 16:59

import bord.fields
import bord.storages.s3
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('columns', models.JSONField(default=list, help_text='List of column and their properties')),
                ('store', bord.fields.ParquetField(blank=True, help_text='The location of the Parquet on the Storage System (S3 or Media-URL)', null=True, storage=bord.storages.s3.S3Storage, upload_to='parquet', verbose_name='store')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the Table was created')),
                ('creator', models.ForeignKey(blank=True, help_text='The creator of the Table', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
