# Generated by Django 3.2.18 on 2023-05-02 10:00

import bord.fields
import bord.storages.s3
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_while', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=2000)),
                ('columns', models.JSONField(default=list, help_text='List of column and their properties')),
                ('store', bord.fields.ParquetField(blank=True, help_text='The location of the Parquet on the Storage System (S3 or Media-URL)', null=True, storage=bord.storages.s3.S3Storage, upload_to='parquet', verbose_name='store')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the Table was created')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_through', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_created_through', to='lok.lokclient')),
                ('creator', models.ForeignKey(blank=True, help_text='The creator of the Table', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
