# Generated by Django 3.2.9 on 2021-11-19 13:35

import bord.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='row_count',
        ),
        migrations.AlterField(
            model_name='table',
            name='store',
            field=bord.fields.ParquetField(blank=True, help_text='The location of the Parquet on the Storage System (S3 or Media-URL)', null=True, storage='bord.storages.s3.S3Storage', upload_to='parquet', verbose_name='store'),
        ),
    ]
