# Generated by Django 3.2.15 on 2022-09-28 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bord', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
