# Generated by Django 3.2.19 on 2023-05-22 14:43

import bord.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lok', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        ('grunnlag', '0006_timepoint_created_at'),
        ('bord', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_while', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=2000)),
                ('used_columns', models.JSONField(default=list, help_text='List of columns of the Table that are used in this Graph')),
                ('image', models.ImageField(null=True, storage=bord.storage.PrivateRenderStorage(), upload_to='graphs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_created_by', to=settings.AUTH_USER_MODEL)),
                ('created_through', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_created_through', to='lok.lokclient')),
                ('datasets', models.ManyToManyField(blank=True, null=True, related_name='graphs', to='grunnlag.Dataset')),
                ('pinned_by', models.ManyToManyField(related_name='pinned_graphs', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='bord.table')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
