# Generated by Django 3.2.9 on 2021-11-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0010_alter_omerofile_type'),
        ('bord', '0003_auto_20211119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='grunnlag.experiment'),
        ),
        migrations.AlterField(
            model_name='table',
            name='representation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='grunnlag.representation'),
        ),
        migrations.AlterField(
            model_name='table',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='grunnlag.sample'),
        ),
    ]
