# Generated by Django 3.2.16 on 2023-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunnlag', '0007_auto_20230207_1256'),
        ('bord', '0003_table_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dataset',
        ),
        migrations.AddField(
            model_name='table',
            name='dataset',
            field=models.ManyToManyField(blank=True, null=True, related_name='table', to='grunnlag.Dataset'),
        ),
    ]
