# Generated by Django 3.2.19 on 2023-05-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0003_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='table',
        ),
        migrations.AddField(
            model_name='graph',
            name='tables',
            field=models.ManyToManyField(related_name='graphs', to='bord.Table'),
        ),
    ]
