# Generated by Django 3.2.19 on 2023-05-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bord', '0004_auto_20230522_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='used_columns',
            field=models.JSONField(blank=True, default=list, help_text='List of columns of the Table that are used in this Graph', null=True),
        ),
    ]
