# Generated by Django 6.0.6 on 2026-10-08 12:54

import chart.enums
import django.db.models.deletion
import django_choices_field.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0007_user_profile'),
        ('core', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_charts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('world', models.ForeignKey(help_text='The space this chart lays its layers out along: a coordinate system with one metric, unit-carrying axis. Never owned by the chart: several charts can share it, it outlives each of them, and deleting a chart never deletes it. RESTRICT: while a chart is laid out over a space, the space cannot be deleted', on_delete=django.db.models.deletion.RESTRICT, related_name='charts', to='core.coordinatesystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('trace', 'Trace (an array read along one axis)'), ('series', "Series (a table's value column against a coordinate column)"), ('annotation', 'Annotation (drawn marks)')], choices_enum=chart.enums.ChartLayerKindChoices, help_text='What this layer reads. Fixed for the life of the row', max_length=10)),
                ('name', models.CharField(blank=True, help_text='A human-readable name for the layer. Null when nobody has named it', max_length=255, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Whether the layer is drawn')),
                ('order', models.IntegerField(default=0, help_text='Explicit drawing order, back to front')),
                ('opacity', models.FloatField(default=1.0, help_text='Layer alpha (0..1)')),
                ('color', models.JSONField(blank=True, help_text='The colour the layer is drawn in, as RGBA. Null to let the viewer choose', null=True)),
                ('value_column', models.CharField(blank=True, help_text="(series) The numeric column read as the value. The coordinate column is not stored: it is the column the table's placement lays along the chart's axis", max_length=255, null=True)),
                ('mark', django_choices_field.fields.TextChoicesField(choices=[('line', 'Line'), ('markers', 'Markers'), ('line_markers', 'Line and markers'), ('steps', 'Steps')], choices_enum=chart.enums.ChartMarkChoices, default='line', help_text='(trace/series) How the values are drawn: a line, markers, both, or steps', max_length=12)),
                ('line_width', models.FloatField(blank=True, help_text='(trace/series) Line width in screen pixels. Null to let the viewer choose', null=True)),
                ('marker_size', models.FloatField(blank=True, help_text='(trace/series) Marker size in screen pixels. Null to let the viewer choose', null=True)),
                ('annotation_collection', models.ForeignKey(blank=True, help_text='(annotation) The collection whose marks are drawn', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_layers', to='core.annotationcollection')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='chart.chart')),
                ('lens', models.ForeignKey(blank=True, help_text='(trace) The lens whose values are read along one of its axes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_layers', to='core.lens')),
                ('table_dataset', models.ForeignKey(blank=True, help_text='(series) The table whose value column is read against a coordinate column', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_layers', to='core.tabledataset')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChart',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='chart.chart')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('world', models.ForeignKey(blank=True, db_constraint=False, help_text='The space this chart lays its layers out along: a coordinate system with one metric, unit-carrying axis. Never owned by the chart: several charts can share it, it outlives each of them, and deleting a chart never deletes it. RESTRICT: while a chart is laid out over a space, the space cannot be deleted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.coordinatesystem')),
            ],
            options={
                'verbose_name': 'historical chart',
                'verbose_name_plural': 'historical charts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalChartLayer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('trace', 'Trace (an array read along one axis)'), ('series', "Series (a table's value column against a coordinate column)"), ('annotation', 'Annotation (drawn marks)')], choices_enum=chart.enums.ChartLayerKindChoices, help_text='What this layer reads. Fixed for the life of the row', max_length=10)),
                ('name', models.CharField(blank=True, help_text='A human-readable name for the layer. Null when nobody has named it', max_length=255, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Whether the layer is drawn')),
                ('order', models.IntegerField(default=0, help_text='Explicit drawing order, back to front')),
                ('opacity', models.FloatField(default=1.0, help_text='Layer alpha (0..1)')),
                ('color', models.JSONField(blank=True, help_text='The colour the layer is drawn in, as RGBA. Null to let the viewer choose', null=True)),
                ('value_column', models.CharField(blank=True, help_text="(series) The numeric column read as the value. The coordinate column is not stored: it is the column the table's placement lays along the chart's axis", max_length=255, null=True)),
                ('mark', django_choices_field.fields.TextChoicesField(choices=[('line', 'Line'), ('markers', 'Markers'), ('line_markers', 'Line and markers'), ('steps', 'Steps')], choices_enum=chart.enums.ChartMarkChoices, default='line', help_text='(trace/series) How the values are drawn: a line, markers, both, or steps', max_length=12)),
                ('line_width', models.FloatField(blank=True, help_text='(trace/series) Line width in screen pixels. Null to let the viewer choose', null=True)),
                ('marker_size', models.FloatField(blank=True, help_text='(trace/series) Marker size in screen pixels. Null to let the viewer choose', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('annotation_collection', models.ForeignKey(blank=True, db_constraint=False, help_text='(annotation) The collection whose marks are drawn', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.annotationcollection')),
                ('chart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chart.chart')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='chart.chartlayer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lens', models.ForeignKey(blank=True, db_constraint=False, help_text='(trace) The lens whose values are read along one of its axes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lens')),
                ('table_dataset', models.ForeignKey(blank=True, db_constraint=False, help_text='(series) The table whose value column is read against a coordinate column', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tabledataset')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical chart layer',
                'verbose_name_plural': 'historical chart layers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='chartlayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annotation_collection__isnull', True), ('kind', 'trace'), ('lens__isnull', False), ('table_dataset__isnull', True)), models.Q(('annotation_collection__isnull', True), ('kind', 'series'), ('lens__isnull', True), ('table_dataset__isnull', False)), models.Q(('annotation_collection__isnull', False), ('kind', 'annotation'), ('lens__isnull', True), ('table_dataset__isnull', True)), _connector='OR'), name='chart_layer_has_the_source_its_kind_names'),
        ),
        migrations.AddConstraint(
            model_name='chartlayer',
            constraint=models.UniqueConstraint(condition=models.Q(('annotation_collection__isnull', False)), fields=('chart', 'annotation_collection'), name='one_chart_layer_per_annotation_collection'),
        ),
    ]
