# Generated by Django 6.0.6 on 2026-08-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalayerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text='The object-store URI of the file', max_length=1000, null=True, unique=True)),
                ('key', models.CharField(help_text='The object key/path within the datalayer bucket.', max_length=1000)),
                ('bucket', models.CharField(help_text='The datalayer bucket/service this store belongs to.', max_length=1000)),
                ('original_file_name', models.CharField(blank=True, help_text='The original client-provided file name.', max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The client-provided content type for the uploaded file.', max_length=255, null=True)),
                ('populated', models.BooleanField(default=False, help_text='Whether the store has been populated with a valid path and is ready for use.')),
                ('max_bytes', models.BigIntegerField(blank=True, help_text='The byte budget the upload grant advertised for this store, recorded so the advertised number and the delivered one can be compared. **Advertised, not enforced**: a session policy scopes what a credential may write, never how much, so S3 accepts an upload that exceeds this and `finish` accepts it as valid', null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='How many bytes this store actually holds, measured when the upload was finished. Null while an upload is unfinished, or for stores written before this was recorded', null=True)),
                ('orphaned_at', models.DateTimeField(blank=True, db_index=True, help_text='When the last data row referencing this store was deleted, or null while it is still in use. A *candidate* for garbage collection, not an authority: `purge_orphaned_stores` re-checks for referrers before deleting anything, and clears this again if the store was re-attached in the meantime', null=True)),
                ('organization', models.ForeignKey(help_text='The organization this store belongs to.', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigFileStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='FabriksStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('spec_version', models.CharField(blank=True, help_text="The mesh format version declared by the store's manifest.", max_length=64, null=True)),
                ('grid', models.JSONField(blank=True, help_text='The octree grid declared by the manifest: cellSize (in voxels, ordered x/y/z), levels and sortKey.', null=True)),
                ('encoding', models.JSONField(blank=True, help_text='The geometry encoding declared by the manifest: how positions, normals and indices are packed and compressed.', null=True)),
                ('axes', models.JSONField(blank=True, help_text='The axis order the writer states it wrote, used to refuse a collection whose declared axes disagree with its geometry.', null=True)),
                ('counts', models.JSONField(blank=True, help_text='Object and per-level cell counts declared by the manifest. Convenience for budgeting; never authoritative.', null=True)),
                ('files', models.JSONField(blank=True, help_text='The file layout the manifest claims. A claim, not authority -- the prefix listing is what a check reads.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='MediaStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='ParquetStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('columns', models.JSONField(blank=True, help_text="The file's own schema, as DESCRIBE reports it: one entry per column with `name`, `type` and `nullable`, in file order. Read off the parquet when the upload was finished, never declared -- a fact derived from the artifact cannot be declared wrong, which is what a column's dtype used to be. Null only for a store written before this field existed, or one whose bytes could not be described.", null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='SparseStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('spec', models.CharField(blank=True, help_text='The version of the `sporadik` block this store was accepted under. A spec selects how every byte in the prefix is read, so an unknown one is refused rather than guessed at', max_length=16, null=True)),
                ('shape', models.JSONField(blank=True, help_text='The shape of the matrix, as the root block declares it and every layout agrees. Two axes', null=True)),
                ('layouts', models.JSONField(blank=True, help_text='The stored layouts, one entry per `layouts/<encoding>` child: its path, `encoding`, `encoding-version`, `nnz`, `dtype` and the chunk length of each of `data`, `indices` and `indptr`. Everything that differs between layouts, and nothing that does not. The chunking is here because it decides the read cost: `indptr` names exactly which bytes a lookup wants and a chunk is the granularity at which they can be fetched, so the two have to agree -- measured on a 16 um matrix, one slice costs 0.95 ms at 32 768-element chunks and 23.55 ms at 4 Mi ones, the same bytes a hundred times over-read', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.CreateModel(
            name='ZarrStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('shape', models.JSONField(blank=True, help_text='The shape of the Zarr array stored at this location.', null=True)),
                ('chunks', models.JSONField(blank=True, help_text='The chunk size of the Zarr array stored at this location.', null=True)),
                ('version', models.CharField(blank=True, help_text='The Zarr format version of the array stored at this location.', max_length=10, null=True)),
                ('dtype', models.CharField(blank=True, help_text='The dtype of the Zarr array stored at this location.', max_length=255, null=True)),
                ('dimension_names', models.JSONField(blank=True, help_text='The dimension names declared by the Zarr array.', null=True)),
                ('fill_value', models.JSONField(blank=True, help_text='The fill value declared by the Zarr array.', null=True)),
                ('attributes', models.JSONField(blank=True, help_text='The user attributes stored in zarr.json.', null=True)),
                ('storage_transformers', models.JSONField(blank=True, help_text='The storage transformers declared by the Zarr array.', null=True)),
                ('chunk_key_encoding', models.JSONField(blank=True, help_text='The chunk key encoding configuration for the Zarr array.', null=True)),
                ('codecs', models.JSONField(blank=True, help_text='The codec pipeline declared for the Zarr array.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
    ]
