# Generated by Django 6.0.6 on 2026-08-31 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonnektionStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('spec_version', models.CharField(blank=True, help_text="The network format version declared by the store's manifest.", max_length=64, null=True)),
                ('grid', models.JSONField(blank=True, help_text='The octree grid declared by the manifest: cellSize (in voxels, ordered x/y/z), levels and sortKey.', null=True)),
                ('encoding', models.JSONField(blank=True, help_text='The geometry encoding declared by the manifest: how positions, edges, node ids, radii and ghosts are packed and compressed, and which coarsening operations each level ran.', null=True)),
                ('axes', models.JSONField(blank=True, help_text='The axis order the writer states it wrote, used to refuse a collection whose declared axes disagree with its geometry.', null=True)),
                ('counts', models.JSONField(blank=True, help_text='Object and per-level cell counts declared by the manifest. Convenience for budgeting; never authoritative.', null=True)),
                ('files', models.JSONField(blank=True, help_text='The file layout the manifest claims. A claim, not authority -- the prefix listing is what a check reads.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
    ]
