# Generated by Django 6.0.6 on 2026-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0002_konnektionstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarrstore',
            name='shards',
            field=models.JSONField(blank=True, help_text='The shard (outer storage object) shape when the array uses zarr v3 sharding_indexed; null for unsharded arrays. When set, `chunks` holds the inner chunk shape.', null=True),
        ),
        migrations.AlterField(
            model_name='zarrstore',
            name='chunks',
            field=models.JSONField(blank=True, help_text="The effective inner chunk shape of the Zarr array — the unit a reader can decode. For sharded arrays this is the sharding codec's inner chunk shape, not the chunk grid's.", null=True),
        ),
    ]
