# Generated by Django 6.0.6 on 2026-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0003_zarrstore_shards_alter_zarrstore_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='konnektionstore',
            name='attributes',
            field=models.JSONField(blank=True, help_text="The per-node value columns the manifest declares, each {name, encoding, semantics}. What a network layer's graph colorBys are validated against; null on a store filled before attributes existed, which reads the same as declaring none.", null=True),
        ),
    ]
