# Generated by Django 6.0.6 on 2026-09-24 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0004_konnektionstore_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayerstore',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who requested the upload grant, whose storage quota the bytes count against. Null for stores written before this was recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
