"""
Django settings for mikro_server project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from .configuration import Settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.django.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = conf.django.debug

if not DEBUG and SECRET_KEY in ("", "changeme"):
    raise ImproperlyConfigured("django.secret_key must be set in config.yaml when django.debug is false")

ALLOWED_HOSTS: list[str] = list(conf.django.hosts)


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "strawberry_django",
    "taggit",
    "channels_redis",
    "guardian",
    "simple_history",
    "authentikate",
    "koherent",
    "kante",
    "channels",
    "django_probes",
    "kanne_server",
    "core",
    "datalayer",
    "health_check",
    "health_check.db",
]


AUTH_USER_MODEL = "authentikate.User"

AWS_ACCESS_KEY_ID = conf.datalayer.access_key
AWS_SECRET_ACCESS_KEY = conf.datalayer.secret_key
AWS_S3_ENDPOINT_URL = f"{conf.datalayer.protocol}://{conf.datalayer.host}:{conf.datalayer.port}"
# AWS_S3_PUBLIC_ENDPOINT_URL = (
#    f"{conf.minio.public.protocol}://{conf.minio.public.host}:{conf.minio.public.port}"
# )
AWS_S3_URL_PROTOCOL = f"{conf.datalayer.protocol}:"
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_EXPIRE = 3600
AWS_S3_REGION_NAME = conf.datalayer.region

ZARR_BUCKET = conf.datalayer.zarr.bucket
PARQUET_BUCKET = conf.datalayer.parquet.bucket
FILE_BUCKET = conf.datalayer.media.bucket
MEDIA_BUCKET = conf.datalayer.media.bucket

AWS_STORAGE_BUCKET_NAME = conf.datalayer.media.bucket
AWS_DEFAULT_ACL = "private"
AWS_S3_USE_SSL = True
AWS_S3_SECURE_URLS = False

GRAPHENE = {"SCHEMA": "core.schema.schema"}

CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(conf.redis.host, conf.redis.port)], "prefix": "mikro"},
    },
}


DATALAYER = conf.datalayer.model_dump(exclude_none=True) if conf.datalayer else {}

# How long a store's bytes survive after the last data row referencing them is deleted.
# `purge_orphaned_stores` (run it from cron) collects anything older; nothing is freed until
# it does. The window exists so an accidental delete is recoverable -- the same job an S3
# lifecycle rule would do, kept in Postgres where it is visible and has minute rather than
# day granularity.
DATALAYER_STORE_GRACE_DAYS = 7

CORS_ALLOW_ALL_ORIGINS = True


CSRF_TRUSTED_ORIGINS = conf.django.csrf_trusted_origins
MY_SCRIPT_NAME = conf.django.force_script_name

STRAWBERRY_DJANGO = {
    "USE_DEPRECATED_FILTERS": False,
    "DEFAULT_PK_FIELD_NAME": "id",
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mikro_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # this is default
    "guardian.backends.ObjectPermissionBackend",
)

WSGI_APPLICATION = "mikro_server.wsgi.application"
ASGI_APPLICATION = "mikro_server.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


AUTHENTIKATE = conf.authentikate.model_dump()


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# WhiteNoise serves static directly from the staticfiles finders at request time
# (works under both runserver and daphne), so no collectstatic / STATIC_ROOT is needed.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


INCREMENTER = "1"
