# Generated by Django 3.2.14 on 2022-09-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(default='\nquery {\n    hello(name: "World")\n}\n\n', max_length=10000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
