# Generated by Django 3.2.16 on 2022-12-16 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the plot', max_length=255)),
                ('description', models.TextField(help_text='A description of the plot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When was this plot created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When was this plot last updated')),
                ('query', models.CharField(default='\nquery {\n    GROUP: experiment(id: 42) {\n      OBJECT: id\n      TYPE: __typename\n      NAME: name\n      \n      GROUP_HYPER_AS_BAD_SAMPLES: samples(tags: "bad") {\n        OBJECT: id\n         TYPE: __typename\n        NAME: name\n        GROUPS: representations(variety: VOXEL){\n          NAME: name\n          OBJECT: id\n          TYPE: __typename\n\n\n          FLATDATUM_OBJECT_AS_INDEX: id\n          FLATDATUM_VALUE_AS_INDEX: id\n          FLATDATUM_TYPE_AS_INDEX: __typename\n  \n          DATUM_AS_TIME: omero {\n            VALUE_FROM_DATE: acquisitionDate\n          }\n          \n          DATUM_AS_EXPOSURE_TIME: omero{\n            OBJECT: id\n            TYPE: __typename\n            VALUE_FROM_SUM: planes {\n              VALUE_FROM_FLOAT: exposureTime\n            }\n          }\n          \n          DATUM_FIRST_AS_INCREASING: metrics(keys: "Increasing"){\n            VALUE_FROM_INT: value\n          }\n          \n          DATUM_FIRST_AS_CELL_AREA: labels {\n            OBJECT: id\n            TYPE: __typename\n            VALUE_FROM_SUM: features(keys: "Area"){\n              VALUE_FROM_FLOAT: value\n            }\n          }\n          \n        }\n          \n        }\n        \n      \n\n      GROUP_HYPER_AS_ELEMENTAL_SAMPLES: samples(tags: "elemental") {\n        OBJECT: id\n         TYPE: __typename\n        NAME: name\n        GROUPS: representations(variety: VOXEL){\n          NAME: name\n          OBJECT: id\n          TYPE: __typename\n\n\n          FLATDATUM_OBJECT_AS_INDEX: id\n          FLATDATUM_VALUE_AS_INDEX: id\n          FLATDATUM_TYPE_AS_INDEX: __typename\n  \n      \n          DATUM_AS_EXPOSURE_TIME: omero{\n            OBJECT: id\n            TYPE: __typename\n            VALUE_FROM_SUM: planes {\n              VALUE_FROM_FLOAT: exposureTime\n            }\n          }\n          \n          \n        }\n          \n        }\n  }\n}\n', help_text='The PlotQL query (see documentation for PlotQL)', max_length=10000)),
                ('creator', models.ForeignKey(help_text='The user who created this plot', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
